version: 2.1

jobs:
  build:
    docker: 
      - image: node
    working_directory: ~/repo
    steps:
      - checkout
      - npm run install
      - npm run test  

workflows:
  build_and_test:
    jobs:
      - build

