version: 2.1

jobs:
  build:
    docker: 
      - image: 14.11.0-alpine3.10
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install npm deps
          command: npm install
      - run:
          name: Run jest tests
          command: npm run test    