version: 2.1

jobs:
  jesttest:
    docker: 
      - image: circleci/node:10
    working_directory: ~/myapp
    steps:
      - checkout
      - run:
          name: Install npm deps
          command: npm install
      - run:
          name: Run jest tests
          command: npm run test    

workflows:
  build_and_test:
    jobs:
      - jesttest         